name: Shrine
description: Learn how to use Material for structure and layout.

environment:
  sdk: ">=2.8.0 <3.0.0"

  
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.15.6
  url_launcher:  ^5.4.0
  url_launcher_web: ^0.1.0
  global_configuration: ^1.6.0
  rive: ^0.7.0




  cupertino_icons: ^0.1.0
  shrine_images: 1.1.1

dependency_overrides:
  url_launcher: '5.4.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_localizations:
  sdk: flutter

flutter:
  # TODO: Insert Fonts (103)
  uses-material-design: true
  assets:
    - assets/diamond.png
    - images/0-0.jpg
    - images/1-0.jpg
    - images/2-0.jpg
    - images/3-0.jpg
    - images/4-0.jpg
    - images/5-0.jpg
    - images/Day.riv
    # TODO: Add slanted menu asset (104)

